### ISSUE TITLE
Toasts for Aragon apps

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#1]
# ✅ Idea

## User story
As as user, I want to have immediate feedback after performing actions.

## Technical requirements
Expose functionality in aragonAPI for apps to show toasts on the user's screen.

## Summary
This functionality will allow the user to have immediate feedback.

Edit: We decided that implementing undo is not a priority, since it wouldn't work with MetaMask (would likely require ad-hoc Frame integration)

# ✅ Prototype/design
[Figma board](https://www.figma.com/proto/QFgvrY5bjKzTY8XqsDmOT9du/Feedback?node-id=66%3A53&scaling=min-zoom)

**Comment by dizzypaty** [comment]
The Toast and ToastHub components are already part of the [aragonUI](https://ui.aragon.org/toast-hub/) toolkit and a toast instance has been implemented when 'coping an address to the clipboard'. 

Here’s the description of its usage, default behavior and a list of use cases where this toast component should be implemented: 

### Description 
The toast component is a non-intrusive message that appears at the bottom of the interface to provide quick, at-a-glance feedback on the outcome of an action. 

Toasts appear briefly and disappear on their own, after 4000ms, without requiring user's input to be dismissed.

Use toasts to convey general confirmation or **actions that aren’t critical**. For example, show a toast to inform the user that their recent changes to Preferences have been saved.

### Best practices 
* Maximum of 2 lines of text.
* The copy should be written in the pattern of: noun + verb (i.e.: Preferences saved)
* Not be used for actionable links or messages.
* Not be used for error messages.
* Generally displayed once at a time. If multiple toasts are triggered, should be stacked on top of each other. 

### Use cases
* Address copied
* Custom label added / saved
* Preferences saved
* Node settings saved
* Application cache cleared
* Transaction signed / cancelled
* Transfers data exported 
* Transfer URL copied
* Future: Logo / profile / bio / description updated

**Note:** More use cases will be added to this list as they are required.

Further design specification of other related Feedback components is currently WIP and can be found in this [document](https://docs.google.com/presentation/d/1vWXyJMNJGSODnyAdIpVRzPsQoufS6K3Ij1nSWiGhf2c/edit#slide=id.g4b0593a6d2_0_51).

This [prototype](https://www.figma.com/proto/QFgvrY5bjKzTY8XqsDmOT9du/Feedback?node-id=66%3A53&scaling=min-zoom) illustrate the toasts that will be displayed to provide quick feedback on the user’s actions – when a transaction is cancel (or rejected) and when a transaction is signed successfully.

**Comment by luisivan** [comment]
As per my conversation with @bpierre:

> still looking for good use cases… none of the ones listed can be added at the moment, for different reasons (e.g. we don’t know when the transfers CSV is copied, the preferences don’t have a save button in their implementation, the node settings are reloading the full window, same for the application cache refresh)

Let's get them out of scope and take this back to design again. @dizzypaty would be cool for you to sync up with @bpierre (after the 0.7 launch of course) about the technical limitations that make the current toast use impossible in the app

**Comment by sohkai** [comment]
Closing this; we will evaluate visual indicators for user feedback in the client later.
