### ISSUE TITLE
One transaction orgs

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#10]
# Idea
## User story
As as user, I want to create my decentralized organization without having to spend much money or wait for too long.

## Technical requirements
To let the user create an organization with just one transaction, instead of two.

- [ ] Limit the user to invite a maximum of people when creating a multisig org. Otherwise, it will go over the gas limit

## Summary

By implementing the creation of organizations with one transaction, we reduce friction and waiting time.

**Comment by sohkai** [comment]
This is related to #24; we can modify the onboarding with those changes so we only need to send one transaction.

**Comment by luisivan** [comment]
Yes, this will fall on a new take on the whole onboarding experience

**Comment by sohkai** [comment]
This has been pulled into the new onboarding for 0.8.
