### ISSUE TITLE
Aragon project + Aragon One blogs readibility

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#101]
# Idea
Make them both more readable

**Comment by ghost** [comment]
@luisivan @delfipolito 
<br/>
I was doing a research of a few blogs with the best experience of readability. And i was take something out:
<br/>
### 1. The text must be in a container of 700px - 720px

### 2.  The font size on paragraphs must be 18px

### 3. The line spacing on paragraphs must be 32px

### 4. The weight on paragraphs must be regular, not light.

![blog_structure.gif](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/4ece36d6-686f-4c60-b99c-73084b2fd3ee)

This is an example with a **720px** on the content and a big pic of header. The text are in 18px and the line spacing is 32px. The weight is regular.

Take a look without guidelines:

![blog_with.gif](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/58030c25-8732-4711-a61c-d7bf240f279b)

Another possibility round my head is the possibility of use a serif type only for the paragraphs, this is a resource that many blogs use (Medium...) 

On this example i tried with the type: Hiragino Micho Pro

![blog_serif.gif](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/81f583f4-e27a-4deb-acb9-707f1754518b)

What do you think?

**Comment by ghost** [comment]
And the same thing with the **A1 Blog**, check how important is the container of the text, this is a example of changing the original **<post-wrap>** of **950px** to **720px.**

https://www.dropbox.com/s/tfl1eosrgv84m0y/A1_READ.mp4?dl=0

Edit: @delfipolito check this modification to A1Blog 👆

**Comment by luisivan** [comment]
@owisixseven this is way better! However, I feel that the font we use now it's too round for reading (maybe we can use a more standard one like https://www.apple.com/newsroom/2019/05/all-new-apple-tv-app-available-in-over-100-countries-starting-today/ or https://www.tesla.com/blog/more-advanced-safety-tesla-owners do), and the serif font looks good, but I don't feel like it fits with the rest of the blog style

**Comment by ghost** [comment]
Good point @luisivan. Agree with the serif font. 

This is a [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro/releases/tag/variable-fonts), a open source font with a very good readability (next to Helvetica).

![source-sans.gif](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/bd38d5e1-02b7-4cac-a4da-9185616e05a4)

**Comment by luisivan** [comment]
This is perfect. Let's implement it cc @delfipolito. Also for the A1 blog?

**Comment by ghost** [comment]
Yes, let's put the same typo into A1 blog. @delfipolito and remember,** this change only affects to the paragraphs texts :)**
