### ISSUE TITLE
Customizable menu bar / app instance labels

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#103]
# Idea
## User story
Instance names like ANT (50%) are not very informative. We need to let DAOs and users modify those.

## Technical requirements
- Treat them as custom labels, display label in menu
- Decide if we want to implement [the past design](https://github.com/aragon/design/issues/21) or a different one

## Frontend
PR: https://github.com/aragon/aragon/pull/824
Branch: `feature/custom-menu-instance-labels`

**Comment by dizzypaty** [comment]
WIP Figma file: https://www.figma.com/file/QHAdtVqXnYpWP7HyVOnjhOCw/Customizable-menu-bar-%2F-app-instance-labels?node-id=0%3A1

**Comment by dizzypaty** [comment]
# Badges & popovers component configurations 

![Badges.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/e39212c1-78d0-4ba8-afc4-a5a4e300bd8b)

![Popovers.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/66f869dc-5c9d-4a0f-a23a-9744f6706f6b)
