### ISSUE TITLE
Update project's roadmap and mark items as done

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#104]
# Idea
## User story
We need to update https://aragon.org/project/roadmap/ and mark some items as done.
Namely:
- Responsive view
- Local identity (custom labels) 
- Finalize Planning Suite
- Upgrading apps from the UI
- Notifications & user feedback

We also need to remove these ones:
- aragonSDK: Split aragonUI and Lorikeet
- Native mobile app
- Incentivisation model for app developers

We also need to add items from the [Aragon Black proposal](https://github.com/aragon/flock/blob/master/teams/Aragon%20Black/2019%20-%20Q3%20%26%20Q4.md) (this will need coordination with @LouisGrx)

## Technical requirements
- Design a "done" state for roadmap items

## Frontend Implementation
[PR](https://github.com/aragon/website/pull/98)

**Comment by ghost** [comment]
@luisivan @delfipolito I added the new label 

![Captura de pantalla 2019-05-28 a las 18.00.52.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/4219110f-a120-48b6-834b-0d3242a69398)
