### ISSUE TITLE
New global settings

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#106]
# Idea
## User story
As as user, I want to have personal global settings that I can clearly differentiate from the DAO's settings. 

## Technical requirements
To let the user have its own settings area, we will implement a new design that will allow us to clearly differentiate the client's area from the DAO's area.

# Design
[Figma board](https://www.figma.com/file/QFizPRIWRn6toUp2mPfg5vRE/Global-preferences-%26-app-settings?node-id=181%3A2)

Iteratiion # 1
---
- [x] https://github.com/aragon/aragon/pull/861

Iteration # 2
---
- [x] ~~https://github.com/aragon/aragon/issues/884~~ (removed from scope for 0.8, see https://github.com/aragonone/product/issues/177)

**Comment by dizzypaty** [comment]
## Global & App specific settings

The following Figma file includes WIP designs for Aragon global preferences: 

* Network settings 
* Custom labels 
* Email settings 
* Help & feedback (opt-out / hide Help Scout module)

Also, a couple of screens showcasing specific app settings (i.e.: Voting app: support, minimum approval % and vote duration)

Next steps are: 

* Complete the Voting app UX enhancements 
* Create a prototype with all voting related changes and conduct usability testing with users 
* Finalize designs on the content related to network & notifications settings. 

[Figma file](https://www.figma.com/file/QFizPRIWRn6toUp2mPfg5vRE/Global-preferences-%26-app-settings?node-id=181%3A2)

**Comment by luisivan** [comment]
Cool! Left some comments on the board
