### ISSUE TITLE
Create StatusPage

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#110]
# Idea

Create a StatusPage for the Aragon client and associated infrastructure.

See product spec: https://www.notion.so/aragon/Infra-Status-Page-ffa41c8b06134ad3abff081386761105

# Implementation
- [x] Create account
- [x] Set DNS so emails come from `noreply@aragon.org`
- [x] Set DNS so it's accessible from `status.aragon.org`
- [x] Set up actual monitoring (see [ideas](https://github.com/aragonone/product/issues/110#issuecomment-495737866))

**Comment by luisivan** [comment]
Any preference on using StatusPage vs other services? I was checking a bit and there are open source alternatives, but I don't think we have the bandwidth to set them up. So I'd just go with either StatusPage or any other easy to setup alternative.

**Comment by sohkai** [comment]
Have no experience with Status Page, but almost every service I've encountered uses it so it seems like a good default choice.

There's almost no point in hosting an open source alternative ourselves for this type of service (hosting + maintenance costs, as well as bundling uptime risk with our own services).

**Comment by luisivan** [comment]
Makes sense. Will proceed with StatusPage

**Comment by luisivan** [comment]
I just set up an account and invited you @sohkai! I can set up the DNS stuff and other things, but in terms of the monitoring, should that be you, or other person in the team?

**Comment by sohkai** [comment]
Will look into it, will likely involve @ji or @2color.

**Comment by luisivan** [comment]
Perfect

**Comment by sohkai** [comment]
A quick investigation:

- It appears we may already use StatusCake to test uptime of a few critical websites (Aragon client, rocket chat, website)
  - StatusPage does not have a built-in integration with StatusCake, but setting this up should be very easy (forward an email to StatusPage on error)
  - Alternatively we could switch to one that is native, e.g. Pingdom, [hexadecimal](https://tryhexadecimal.com/)
- Node uptime
  - We could upgrade our OpsGenie instance from free to ~$100/month to integrate prometheus alerts into incident reports on StatusPage
    - Not sure how our prometheus alerts are set up and how easy it would be to filter for relevant events :man_shrugging:
    - Not sure if we could directly send emails or run a small service ontop of alertmanager to push data into StatusPage
  - We should run another small service that just periodically (every ~1min) checks our node's blockheight against infura or etherscan's (e.g. [similar one built for new relic](https://github.com/identity-com/ethereum-node-healthcheck)), and plot the diff as a custom metric
    - This (and the website uptime checks) could be done via a CI-server allowing recurring actions, e.g. [buddy](https://buddy.works/guides/automate-monitoring)

**Comment by luisivan** [comment]
Thoughts about just using StausCake's page? https://pages.statuscake.com/landing_page/
