### ISSUE TITLE
Add HackerOne security testing / advisory

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#111]
# Idea

Leverage [HackerOne](https://hackerone.com/) to increase security testing, especially on the frontend.

## Technical requirements

Set up a HackerOne profile (e.g. see [their own](https://hackerone.com/)) with the relevant details and explore bug bounty / pen testing.

**Comment by luisivan** [comment]
Just created an account and a profile. It's pending verification by HackerOne now. After that, I can invite you to the account so you can do any fine-tuning that needs to be done

**Comment by luisivan** [comment]
@izqui let me know next steps if any

**Comment by izqui** [comment]
I had a call with Hacker One and they demo'd me their [Bounty](https://www.hackerone.com/product/bounty) product, thinking that we wanted to run our current bug bounty program (just smart contract code). They have two variants for this product, managed or unmanaged, in the case of managed Hacker One would triage reports as they come in. The yearly fee is quite high in my opinion (25k/y for unmanaged and 35k/y for managed). Hacker One would also take care of the payouts for valid reports.

In my opinion, we would only have more visibility for the bug bounty program, and the hacker audience in Hacker One is not specialized in smart contracts, so we may not get a lot of benefit. Currently we are not getting a lot of reports through the bug bounty program, but I believe that if we publicized it more we could get most of the benefits of running it on Hacker One.

I also talked to @sohkai about using [Hacker One Challenge](https://www.hackerone.com/product/challenge) to do a one time pen-test of the client. I think that something like this should be deferred until after 0.8 has been released. What do you think?

**Comment by sohkai** [comment]
Agreed, I don't see any benefit to us doing the bounty program through them for smart contracts (originally "bug bounty" was meant for the frontend and additional centralized services we maintain—I should've been more clear).

> a one time pen-test of the client

Totally agreed we can delay this, but we should think more and more about it over the next year.

------

I asked Martin (from CD) about what his impressions of the opsec community had around HackerOne, and he was fairly positive, and suggested that having a profile there with contact information is a good starting point.

I can't find our profile (@luisivan has it been approved yet?), but it doesn't hurt to keep this updated with relevant details in case someone looks to file a report to us through HackerOne.

**Comment by luisivan** [comment]
It should be up at https://hackerone.com/aragon_association/. LMK if anything else needs to be done there

**Comment by sohkai** [comment]
Trying to visit the page results in either a sign-in or not found page. Is there a way to make it public?

**Comment by luisivan** [comment]
I don't see any option to make it public -- @izqui did they mention anything about this in the call?

**Comment by izqui** [comment]
No, I will ask.

**Comment by luisivan** [comment]
Thanks very much for reaching out to HackerOne. I see you have requested to invite hackers and go live with a private program.

Just got this email:

> After review, your program (aragon_association) is missing some key required elements for approval. In order to start a HackerOne program, you must have:
> - A valid Disclosure Policy
> - A valid attack surface for researchers to hack that is defined in your program's scope
> - A verified email address that matches your company domain

I don't understand how the relevant docs we sent don't satisfy those. I don't think getting in touch with them has a lot of leverage if they cannot figure out how to verify our profile for like one month

**Comment by sohkai** [comment]
If we've already sent https://wiki.aragon.org/dev/security/ over to them and that's what we got back, it sounds like we can pause this effort until we want to engage further.

**Comment by luisivan** [comment]
Sounds good

**Comment by sohkai** [comment]
Closing; this did not look feasible and does not provide very much value.
