### ISSUE TITLE
Intent accumulator (aka shopping cart)

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#12]
# Idea
## User story
As as user, I want to vote on a bunch of different proposals, like those in the AGP process for the Aragon community.
I also want to be able to upgrade all my organizations' apps seamlessly without having to go one by one.

Related issues: [1](#)

## Technical requirements
The functionality is already there in aragonOS, But to let the user perform multiple actions at once, we need a *shopping cart* user interface.

## Summary

By implementing a *shopping cart* user interface, we allow the user to perform multiple actions without having to sign and pay for multiple transactions.

**Comment by sohkai** [comment]
Closing here; we will track this in the client repo.
