### ISSUE TITLE
Simple recovery app for edge cases

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#128]
# Idea
## User story
As a user, I may run into a number of edge cases that are either difficult or cumbersome to recover from in the Aragon client, and want to use a frontend to fix the issue. I may not be comfortable using a CLI, or the functionality may not be available in the CLI (too difficult to include, or not yet added).

A few cases:

- Multi-transaction templates: sent transaction X of Y (e.g. created token, but not yet the org), causing the user to "waste" money
- Recovering tokens / ETH from apps

## Technical requirements

To reduce the cost (design and implementation), offer a simple web app that allows users to troubleshoot and fix their problem. It should be integrated with web3 to allow the user to directly send transactions, but should also offer the ability to display the raw transaction data in case they need to sign it offline.

**Comment by luisivan** [comment]
About multi-tx templates: wouldn't be better that the onboarding naturally supports recovering from incomplete states? We could store them in localStorage.

About recovering tokens from apps: what would this imply?

**Comment by sohkai** [comment]
> wouldn't be better that the onboarding naturally supports recovering from incomplete states? We could store them in localStorage.

Yes, now that this is more of a reality than I was anticipating before making this issue, we will likely have to do this in the client itself. There are a few different tradeoffs, but the biggest:

- Client: user will have to use the same browser instance to recover, a bug / crash could lead to invalid state resulting in "lost" money
- Other app: we could do various "smart" things to help users recover just by taking their address, but the up-front technical cost and complexity (with more generic 2+ tx templates) will be higher

> About recovering tokens from apps: what would this imply?

Users _can_ send tokens to an app today. If they do, the contracts support an "escape hatch" hook to recover those funds into the default vault (by default there is only one, hooked up to the Finance app). There is no "protection" (in the way of permissions) on this recovery action; any one can invoke it.

A frontend could receive the app address and token address and check if the app owns any tokens. If it does, expose a button to the user to invoke this recovery.

**Comment by sohkai** [comment]
We will evaluate this in the future. This is currently alleviated by the fact that we have mostly one-transaction templates and recovery can be handled through the in-app console.
