### ISSUE TITLE
Tollgate Forwarder

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#130]
# Require users to pay a fee to perform an action

## User story
As an organization I want to allow certain actions, like submitting a vote, to be publicly accessible but come with a cost in order to prevent spam and ensure the action is well considered. 

## Technical requirements
- Should be initialized with `token address`, `amount`, `destination address`
- Should implement a function to change `amount` protected by a role `CHANGE_AMOUNT_ROLE`
- Should implement a function to change `destination address` protected by a role `CHANGE_DESTINATION_ROLE`
- We do not need to implement a full UI for this because the user will never need to interact directly. It can be used strictly via Permissions, Transaction Pathing, and the signer panel.

## Implementation
Working [repo](https://github.com/aragonone/tollgate)

- [x] Implement contracts (sprint 19)
- [x] Review contracts (sprint 20)
- [x] Write tests (sprint 20)
- [x] Implement sample kit (sprint 20)
- [x] [aragon.js change](https://github.com/aragon/aragon.js/issues/338)
- [x] Final review?
- [x] Test in Rinkeby

**Comment by luisivan** [comment]
UI-wise, will this use triggers? Or would the fee payment just work out of the box with transaction pathing, and just ask the user for a fee when forwarding?

**Comment by lkngtn** [comment]
> UI-wise, will this use triggers? Or would the fee payment just work out of the box with transaction pathing, and just ask the user for a fee when forwarding?

The latter, it will prompt the user for an approval, and the forwarder will make the transfer before forwarding the intent.

**Comment by luisivan** [comment]
Got it. So no changes needed in the signer panel? Should it work out of the box?

**Comment by lkngtn** [comment]
cc @sohkai 

I believe there will need to be a small change in AragonAPI to allow the forwarder to request the approval separate from the intent.

**Comment by sohkai** [comment]
@lkngtn @luisivan Yes, we need to do a little bit of reworking for the "pretransactions" API in `@aragon/wrapper` so this will come with an Aragon client upgrade (most likely 0.8 unless we release 0.7.6 with a few small non-user facing upgrades like this).

**Comment by sohkai** [comment]
Closing; this is ready for mainnet deployment and we will wait for a use case to present itself before we do audits and deploy.
