### ISSUE TITLE
Approvals App

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#131]
# Allow intents to be forwarded only after a role-based approval process

## User story
- As an organization I want to require two distinct stakeholders groups to approve of an action before it can be performed. 
- As an organization I want to assign a group of moderators to evaluate proposals before they are voted on. 

Related prototype:
https://github.com/aragon/aragon-apps/tree/approvals_app/future-apps/approvals

## Technical requirements
- Should not require initialization parameters
- Should implement a  `Submit` function protected by a role `SUBMIT_ROLE`
- Should implement a `Reject` function protected by a role `REJECT_ROLE`
- Should implement a `Approve` function protected by a role `APPROVE_ROLE`
- Should provide a UI, similar to the voting app, showing submitted proposals with buttons for approval or rejection.
- The application is likely to be configured such that actions will need to forward through a subsequent voting app. It is important for the user to be able to see information about the full transaction path and not just the next action in the forwarding path (eg create vote). 

## Implementation
Working [repo](https://github.com/aragonone/approvals)

- [x] Contracts implementation (sprint 20)
- [x] Sample kit for development (sprint 20)
- [x] Frontend implementation (sprint 20)
- [x] Decode N-depth forwarding actions in aragonJS - [PR 337](https://github.com/aragon/aragon.js/pull/337) (sprint 21)
- [x] Review contracts implementation
- [ ] Review front-end implementation
- [ ] Test in Rinkeby

**Comment by sohkai** [comment]
> It is important for the user to be able to see information about the full transaction path and not just the next action in the forwarding path (eg create vote).

This is the part where we'll need to do a bit more work in `@aragon/wrapper` cc @facuspagnuolo @luisivan.

**Comment by sohkai** [comment]
Closing; this was staged for deployment and we will wait for a use case to present itself before working further on it.
