### ISSUE TITLE
Add reference field to token manager actions

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#132]
# Add a reference field to token manager actions (mint, burn)

## User story
As an organization I have the mint and burn actions require a vote and want to be able to differentiate proposals based on a reference field. 

Related issues: 
https://github.com/aragon/aragon/issues/841

## Technical requirements
- The reference field should be visible within forwarders like the voting app.

**Comment by luisivan** [comment]
Does this require contract changes or just frontend changes? @lkngtn @sohkai

**Comment by sohkai** [comment]
This would require at least one of the following changes:

- Metadata included in the token manager's actions (fairly trivial, but adds to gas costs and would be somewhat painful to upgrade to)
- Additional forwarder flexibility (e.g. https://github.com/aragon/aragon/issues/452; fairly large cost)
- A way to sync forwarding metadata across orgs (Autark has a similar problem, but solving this without relying on a centralized server is unclear)

**Comment by lkngtn** [comment]
> A way to sync forwarding metadata across orgs (Autark has a similar problem, but solving this without relying on a centralized server is unclear) 

@sohkai do you have a link to where this issue has been discussed, would be great to have some additional context.

**Comment by sohkai** [comment]
@lkngtn Not really... as far as I know it's mostly working off of https://github.com/aragon/aragon.js/pull/314, and it's unclear to me if this metadata API is what we're looking for.

But in the general case, if we could sync a metadata blob across organizations, it's conceivable that users would be able to add information to it to annotate forwarding actions (I imagine discussions would work fairly similarly).

**Comment by sohkai** [comment]
Closing here; we will track this in the client repo.
