### ISSUE TITLE
Automate code review with bots

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#139]
Multiple alternatives:
- https://github.com/marketplace/codelingo
- https://github.com/marketplace/codebeat
- https://github.com/marketplace/hound
- https://github.com/marketplace/code-climate
- https://github.com/marketplace/codacy

**Comment by sohkai** [comment]
Generally I don't find these tools very useful for our current stack.

For JS, we already use ESLint and prettier, and there's not so many things these automated tools would be able to detect that aren't already caught by the commit + push git hooks. Most of the trickier details need human review; no computer (today) is going to tell you an abstraction seems to be leaky like a human could.

For solidity, almost all of the automated vulnerability tools and scanners cost more time triaging false positives than actually being useful.

**Comment by luisivan** [comment]
Got it -- good to know. Closing this
