### ISSUE TITLE
Autark: Whitelisted token

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#145]
# Idea
## User story

Autark would like to create a whitelisted token, for use cases such as bountying reputation (only a certain whitelisted group of addresses can initiate transfers / mints).

They should be ready for it to be reviewed by July 15th.

**Comment by luisivan** [comment]
Makes sense -- just to clarify, we would just need to review from our end, right @sohkai?

**Comment by sohkai** [comment]
Yes, mostly to coordinate and review.

**Comment by sohkai** [comment]
Closing; AFAIK this was done but no PR ever surfaced.
