### ISSUE TITLE
Support alternative Test Networks

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#146]
# Idea
## User story
If we expect app development teams to integrate Aragon it would be helpful if we maintained deployments on the test network that the project is already using to minimize friction points. 

Currently we only deploy to the Rinkeby test network, while Rinkeby is popular, some other projects only develop and test on Ropsten or Goerli. It would be helpful for us to maintain a basic deployment of Aragon infrastructure on these other test networks. Ropsten in particular has come up in conversations with other projects. 

If a project is using one of these networks, we are basically asking them to redeploy their full stack and change their workflow over to Rinkeby in order to experiment/test Aragon. 😿

We can treat additional test net deployments like Staging, with less strict requirements for deployments.

## Technical requirements
* Deploy and maintain the base system
	* aragonPM
	* apm-serve
* Deploy upgrades to client and apps 
* Deploy onboarding portal (not strictly necessary if it saves time, users can use the CLI to deploy test orgs)
* Get an AlchemyAPI/Infura key, and reroute all not-mainnet requests there
* Keep supporting mainnet and Rinkeby, and unofficially/under request support other networks such as Ropsten or Kovan

**Comment by sohkai** [comment]
Autark has at least suggested they may be interested in maintaining the Goerli deployment (along with running its nodes).

Ropsten and Kovan could be useful. The main pain point with Ropsten earlier was with low gas limits; this seems to be a non-issue now since it looks like they're at 8m gas as well.

**Comment by luisivan** [comment]
Goes into the bigger conversation of continuous deployments -- will check in to see what we can do here

**Comment by lkngtn** [comment]
If this is feasible it would be great to nail down a timeline for being able to deploy to Ropsten. We are talking with Decentraland and all of their infrastructure and testing happens on Ropsten, so if they want to test integrating Aragon it would need to happen on Ropsten.

**Comment by sohkai** [comment]
We can certainly deploy it as soon as we'd want; it'd take about 2-4 hours for someone to deploy all the contracts to just one network. Maintaining it is the real pain point.

**Comment by luisivan** [comment]
In terms of deployment, we could sprint this for next week if it's urgent @lkngtn. @sohkai who are the persons who could work on this? I think best would be @izqui since he's not with 0.8 stuff.

**Comment by sohkai** [comment]
Yes, @izqui would definitely be the go-to since he's deployed the last two networks 😄

**Comment by izqui** [comment]
As @sohkai said, the on-chain deployment itself would be 2-4 hours. From the maintenance point of view, I definitely wouldn't create the expectation that the Ropsten deployment will always be up to date with Rinkeby and Mainnet for now, at least until we have a more automated process for doing this. 

Regarding the infrastructure required, we would need a Ropsten node (or maybe use the opportunity to try out Alchemy #147). Updating the apm-serve configuration to add the new network should be pretty straightforward, specially if we don't want to have a `ropsten.aragon.org` URL but just use apm-serve directly (it would be `aragon.ropsten.aragonpm.com`, similar to staging). If we go this route, I wouldn't even update the network selector in the client's onboarding for now.

**Comment by lkngtn** [comment]
I think if we can get this deployed by the end of next week that would be good timing and keep momentum. We can certainly set expectations that while we can initially get it deployed we don't necessarily have a definite process for ongoing maintainence and the deployment may not always be in sync with rinkeby.

**Comment by luisivan** [comment]
Will find a way to make this happen during next week @lkngtn

**Comment by luisivan** [comment]
I think we could do the following:
- Officially support Mainnet and Rinkeby
- Unofficially support Ropsten and Kovan (aka deploy it under request only when needed, may not be up to date)
- Have Autark support Goerli if they want
- Use Alchemy for all endpoints that are not Mainnet, even stop running our own Rinkeby node (as suggested by @sohkai)

**Comment by sohkai** [comment]
Alternatively we just get an Infura key and reroute non-mainnet traffic to Infura, because testnets are not value-bearing.

Infura is _fast_ at getting logs; using a testnet version would almost feel as fast as a local chain on load.

**Comment by luisivan** [comment]
Agree. Will update the OP to reflect this

**Comment by sohkai** [comment]
@luisivan The ropsten deployment has been completed, but the question lies in which other test networks we'd like to support.

Perhaps we can open new product issues for those other networks as their need arises?

**Comment by sohkai** [comment]
Closing as Ropsten has been deployed; we can support other networks on a case-by-case basis.
