### ISSUE TITLE
Try out AlchemyAPI

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#147]
# Idea
## User story
As Aragon One, we want to minify the amount of time we spend on infra so we can focus on product.

## Technical requirements
Find an alternative to running our own node that gives us the reliability and performance we need.

**Comment by 2color** [comment]
I ran an experiment comparing infura to Alchemy and our node. 

By now we know that the most expensive calls tend to be the `getLogs`. Therefor I crafted the following request fetching from block `6702074`

```javascript
const governanceVotingAddress = '0x277bfcf7c2e162cb1ac3e9ae228a3132a75f83d4'
const requestBody = {
  jsonrpc: '2.0',
  id: 1,
  method: 'eth_getLogs',
  params: [
    {
      fromBlock: '0x6643fa',
      address: governanceVotingAddress,
      topics: []
    }
  ]
}
```

```
┌─────────┬────────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────────┐
│ (index) │        wait        │        dns         │        tcp         │     firstByte     │     download      │       total        │
├─────────┼────────────────────┼────────────────────┼────────────────────┼───────────────────┼───────────────────┼────────────────────┤
│ alchemy │ 20.450117999999975 │ 32.702432000000044 │ 119.95065999999997 │   32095.938371    │ 494.3267719999967 │ 32763.368352999998 │
│ infura  │ 1.239734999999996  │      47.1807       │ 118.39970299999993 │ 616.3057900000001 │    596.993323     │    1380.119251     │
└─────────┴────────────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────────┴────────────────────┘
```

The results are in `ms`. 
The connection to our node timed out multiple times. 


## Summary 

Infura's results are significantly better. Probably because they're serving getLogs requests from a caching layer rather than an actual node.

**Comment by luisivan** [comment]
Interesting. So based on this Infura > Alchemy > our node?

**Comment by 2color** [comment]
> Interesting. So based on this Infura > Alchemy > our node?

Infura > Alchemy - Definitely

Alchemy > our node - I don't have a definite answer. It could very well be an http timeout problem.

**Comment by luisivan** [comment]
Closing this for now, as Infura seems to be working faster for us than Alchemy, and we don't have much bandwidth to work alongside them to optimize it
