### ISSUE TITLE
Redesign for landing page

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#149]
# Idea
New version of the landing page

# Copy

- [ ] Sign-off (Sprint 29 @john-light)

# Implementation

- [x] Home
- [x] Navbar
- [x] Footer
- [x] Network
-  [x] Discover
- [x] Project
- [x] Governance
- [x] Grants
- [x] Contribute
- [x] Roadmap
- [ ] Developer portal

**Comment by ghost** [comment]
Hey @luisivan @john-light you have here the first draft to create the copies - https://www.figma.com/file/SuleuupZMJrCFFFhQGRscNzK/hackaton?node-id=0%3A1
