### ISSUE TITLE
Upgrade apm-serve

### ISSUE THREAD

**Issue by 2color** [aragonone/product#150]
# Idea
## User story
Add security headers, instrumentation, and performance improvements to apm-serve

Related issues: 
- https://github.com/aragon/apm-serve/pull/26
- ~https://github.com/aragon/apm-serve/pull/29~ (done already)

## Technical requirements
- [x] Get the pull request https://github.com/aragon/apm-serve/pull/26 merged
- [x] Make sure the docker image is built for master and pushed to docker hub
- [x] Update the image tag on production.

**Comment by izqui** [comment]
Just submitted a PR adding the Ropsten configuration. It would be good to upgrade it all at the same time: https://github.com/aragon/apm-serve/pull/30

**Comment by 2color** [comment]
Just deployed master, built the image manually and deployed to get ropsten support out. 

Will handle the rest next week
