### ISSUE TITLE
Deploy Aragon on Ropsten

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#152]
Reference: https://github.com/aragonone/product/issues/146

**Comment by luisivan** [comment]
@lkngtn Ropsten deployment will happen during tomorrow, @izqui is scheduled to work on it

**Comment by izqui** [comment]
I will actually work on it tomorrow instead as we need some infrastructure in place for the deployment.

- As mentioned in #146, we need an endpoint for a Ropsten node. I think it makes sense to proxy `wss://ropsten.eth.aragon.network/ws` to Infura for now cc @2color 
- We need to prepare aragon/aragon for adding the ropsten network configuration cc @sohkai

**Comment by sohkai** [comment]
https://github.com/aragon/aragon/pull/866 adds support for Ropsten in aragon/aragon.
