### ISSUE TITLE
Work on design for fundraising onboarding

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#156]
# Idea
## User story

The current fundraising onboarding designs are based purely on the the fundraising app and its initialization parameters. 

However, setting these parameters can be unintuitive for users. It would be great if we could provide an fundraising initialization "phase" to improve onboarding experience for the common fundraising case where a project has a minimum fundraising goal and burn rate in mind. 

Rather than have the user try and understand the raw initialization parameters, this would have the user specify some more intuitive variables and then infer what the curve initialization parameters need to be:
- A minimum funding goal
- A funding deadline 
- Initial price per token 
- Percent of initial supply offered
- Tap rate
- Vesting Schedule 

Related issues: 

## Technical requirements
The following doc is being used to document this flow and technical requirements. 
https://docs.google.com/document/d/1CUyTxDOJIum1ea_PLjhYWZ2qPeSzuIIBjHHcI_h5aUc/edit#

**Comment by luisivan** [comment]
@lkngtn can you help me fill the issue description here? Thx!

**Comment by lkngtn** [comment]
Added a basic description, and included the link to  the document that we are currently using to get feedback on.
