### ISSUE TITLE
0.8 Launch video

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#164]
# Idea
## User story

As as user, I want the [most hype video introduction](https://gph.is/2z1MoOb) to 0.8

## Implementation

- [ ] Luis to sign off (@sprint 29)
- [ ] John to sign off (@sprint 29)

**Comment by ghost** [comment]
V1
https://www.dropbox.com/s/z6dlvfcr8ha68uy/Versi%C3%B3n_CORTA.mov?dl=0

**Comment by luisivan** [comment]
This one has been finished https://www.dropbox.com/s/61t99x1jbey18y2/0.8Camino.mp4?dl=0
