### ISSUE TITLE
Aragon One website

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#17]
# ✅ Idea
## User story
As as Aragon community member, I want to read more about Aragon One and how they operate.

As a possible candidate for Aragon One, I want to read about work conditions, see openings and apply to them.

## Technical requirements

Implement a new website at aragon.one.

## Summary

By implementing a new website, community members and candidates can inform themselves about the company.

# ✅ Design
[Figma board](https://www.figma.com/file/EsFoMSGdKpwMHqVPeRztY4zs/Aragon-One?node-id=0%3A1)

# ✅ Frontend Implementation
[Working Branch](https://github.com/aragonone/website/tree/redesign) 
[PR](https://github.com/aragonone/website/pull/2)

**Comment by luisivan** [comment]
@delfipolito is there any staging URL so I can review?

**Comment by delfipolito** [comment]
No, the only way for now is to pull the PR changes and test it locally
