### ISSUE TITLE
Token Wrapper Frontend

### ISSUE THREAD

**Issue by lkngtn** [aragonone/product#173]
# Idea
## User story

The following guide https://forum.aragon.org/t/guide-using-a-vanilla-erc20-token-with-aragon/1000 describes a process for installing a Token Wrapper app that allows users to lock an ERC20 token and generate a minime voting token to use with Aragon. 

However, there is currently no front-end for interacting with the token wrapper contract. It would be really useful to provide a basic frontend that allows the user to 1) deposit tokens and generate voting tokens 2) redeem voting tokens for locked tokens. 

This is something that would be broadly useful to have available, and specifically required for an upcoming launch. 

Related issues: 

## Technical requirements

-------

- [x] Schedule kickoff (sprint 34)
- [x] @ajsantander to finish contracts (Sprint 34)
- [x] @delfipolito to begin frontend (Sprint 34)
- [x] @dizzypaty to implement design changes (Sprint 35)
- [x] @delfipolito to finish frontend (Sprint 37)
- [x] @bpierre to review frontend (Sprint 37, Sprint 38)
- [x] @sohkai to review scripts (Sprint 37)
- [x] @sohkai to finalize contracts + permissions (Sprint 38)
- [x] Deploy to Rinkeby on `open` (Sprint 38)
- [x] @sohkai to decide on audit strategy (Sprint 38)

## Frontend implementation
- https://github.com/aragonone/token-wrapper/pull/4

**Comment by lkngtn** [comment]
Berlin Blockchain week ended up being quite packed, I didn't have a chance to work with Paty on mockups yet. We are starting the testing process on rinkeby this week with decentraland, they are expecting to test without the token wrapper UI, but I expect testing may go pretty quickly so would be great to get this moving this coming sprint. :)

**Comment by lkngtn** [comment]
WIP Design: https://www.figma.com/file/K2dBMGpDmC6s9zSyHV3AqZ/Token-Wrapper?node-id=0%3A1

**Comment by luisivan** [comment]
Love this

**Comment by eternauta1337** [comment]
Update: I submitted a PR with a basic connection of the token-wrapper app to an ultra basic UI: https://github.com/aragonone/token-wrapper/pull/2

We should elaborate on it with @delfipolito and later submit for review to @bpierre
