### ISSUE TITLE
Upgrade Discourse

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#191]
Upgrade Discourse to latest version. [Link to private Flow task](https://app.getflow.com/organizations/379226/teams/359612/tasks/43671352)

**Comment by izqui** [comment]
This one is trivial, I can do it myself in a minute

**Comment by luisivan** [comment]
@john-light told me the automatic upgrade doesn't work -- but let me know if you can do the manual one

**Comment by izqui** [comment]
Done
