### ISSUE TITLE
Post 0.8 tasks (Pierre)

### ISSUE THREAD

**Issue by bpierre** [aragonone/product#195]
- [x] Finalize template format ([PR](https://github.com/aragon/aragon/pull/1057))
- [x] Fix prop types warnings ([PR](https://github.com/aragon/aragon/pull/1059))
- [x] Fix orange glow of Modal on Chrome ([PR](https://github.com/aragon/aragon/pull/1068))
- [ ] Review fundraising
- [ ] Deployment screen: fix header buttons
- [ ] Onboarding: fix full width on the welcome screen
- [ ] Finish carousel gesture
- [ ] Apps paths (deep linking)
- [ ] Account module popover
- [ ] Favorites: don’t update live on Onboarding + save live on OrgView
- [ ] Make the dark theme work (update colors in aragonUI as needed)
- [ ] Upgrade Parcel / fix GitHub security warnings / update ESLint etc. everywhere
- [ ] Refactor routing
- [ ] Finish migrating Wrapper => OrgView
- [ ] Implement transactions manager
- [ ] Deployment screen: contextual errors
- [ ] Prepare aragonUI 1.0:  cleanup + colors + text styles + useTheme() + docs + short blog post. Optional: babel plugin + web + long blog post.

**Comment by izqui** [comment]
The table in Finance feels really cramped when there are long descriptions:

<img width="1101" alt=" 2019-09-16 at 1 39 28 PM" src="https://user-images.githubusercontent.com/447328/64955043-7a90b800-d887-11e9-85dd-1a730c5d703a.png">

I'd really avoid new lines in the 'Amount' field unless the token symbol is really long

**Comment by bpierre** [comment]
Agreed, even with long token symbols / amounts, I think an amount should always stay on one line and use an ellipsis if needed.

**Comment by AquiGorka** [comment]
@bpierre with `DataView`'s current implementation it is very hard to do the text overflow dance without a set `max-width`. Any idea on how to go at this?
