### ISSUE TITLE
Export finance CSV

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#20]
*To be documented*

# ✅ Design

[Figma board](https://www.figma.com/file/gG7CRcw9ecBJ3bUxd4oNa5Qq/Export-data?node-id=1%3A850)

# ✅ Frontend implementation

- [x] Review by @bpierre

**Comment by jounih** [comment]
**Design:**

https://www.figma.com/file/gG7CRcw9ecBJ3bUxd4oNa5Qq/Export-data?node-id=1%3A850

**Comment by AquiGorka** [comment]
❤️ 
@jounih I think the designs for mobile are missing the range picker.
