### ISSUE TITLE
Fundraising launch video

### ISSUE THREAD

**Issue by ghost** [aragonone/product#202]
# Idea
As a user, I want a short (00:20-00:45) introduction video for Fundraising showing all the features.

Sprint 34: review from Jack

**Comment by ghost** [comment]
https://www.dropbox.com/s/w76frzvxna9dh81/Fundraising_draft_01.mp4?dl=0

**Comment by 0xGabi** [comment]
@owisixseven I love it!!

I have a small feedback, it was difficult to keep up with some of the text between seconds 25 to 28. 

The specific text displayed by frame was: 
1. oriented projects with **long-term**
2. objectives
3. that require **ongoing**
4. founding

I missed the bold text the first time.

**Comment by ganeJackS** [comment]
Video is looking super clean, @owisixseven !  Sorry being so late on this as well.

I feel like the copy pulled from the landing page doesn't quite fit the rhythm of the video like we'd hoped. Let me know what you think of the copy below. 

1. What if crowdfunding could be safe? accountable? sustainable? global?
2. Introducing Aragon Fundraising, Fair and sustainable fundraising for all
3. A new type of crowdfunding system 
4. where funders can recovery their money whenever they want, 
5. and fundraisers protect their reputations, while crowdfunding their ideas
6. ideal for global communities, that need ongoing funding, and fair transparent governance

**Comment by ghost** [comment]
Hey, here the last video with the new copy! -> https://www.dropbox.com/s/8nxywzdgkj26e78/Master_001.mp4?dl=0

**Comment by ganeJackS** [comment]
Quick typo fix, "can recovery their" => "can *recover* their"
