### ISSUE TITLE
Fundraising Discovery Platform 

### ISSUE THREAD

**Issue by dizzypaty** [aragonone/product#204]
# Idea

Discovery platform for raising awareness and funds for dapps and projects. 

- Curated projects can get long term funding support through the Fundraising app 
- Design solution needs to consider two different actors and user journeys: projects & patrons
- Possibility of white-labeling this platform in the future for other use cases (bounty platform, domain specific DAO explorer)

## Related docs: 

* ECF & Status as launching partners –  https://quip.com/t01DAOhNvX69
* [Initial visual exploration](https://www.figma.com/file/RLcSiZx2Y230cxgd9CH2a6/Discovery-Platform---Fundraising?node-id=0%3A1&viewport=-387%2C468%2C0.25) to use as a marketing tool during the Asia tour. It contains 3 key screens: landing, projects list and project detail page.

## Design tasks 
- [x] Review marketing materials for Asia Tour Jack (Sprint 35)
- [ ] Wrap up initial research into fundraising platforms
- [ ] Define scope & info gathering activities; competitive analysis + ECF/Status requirements; check in with Maria
- [ ] Initial concepts & user journeys 
- [ ] Usability testing & feedback from potential users (Asia tour)
- [ ] Define branding 
- [ ] Review & kickoff with engineering

**Comment by sohkai** [comment]
Closing; we will not be pursing a discovery platform for fundraising at this moment.
