### ISSUE TITLE
SDK: roadmap

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#217]
# Idea

As as user, I want the simplest and easiest CLI experience possible when interacting with Aragon using the CLI.

aragonCLI has so far lacked a managed roadmap, outside of a [non-prioritized and outdated internal roadmap](https://github.com/aragon/aragon-cli/blob/master/docs-internal/Roadmap.md).

**Appetite**: Three weeks (paused; last week at the offsite + later to regroup)
**Outcome**: A 3-6 month roadmap for the CLI the team is committed to

## Objectives

The three main objectives in setting out a new roadmap for aragonCLI are:

1. **Becoming confident**: evaluate the current implementation and its exposed interfaces, but not be afraid of rewriting or changing vast portions of the existing codebase
1. **Forming opinions**: decide, with conviction, how we intend users to use the CLI and what tasks to optimize for 
1. **Expanding our sights**: begin thinking about how we could _dramatically_ improve user experiences, with potentially new tools for the Aragon ecosystem. We should look at what others have done to create delightful development experiences (e.g. `create-react-app`, `zeppelinOS`).

## Requirements
1. **Becoming robust**: the CLI should "just work<sup>TM</sup>". The rate of errors or failing commands must be dramatically decreased.
1. **Obsessive simplicity**: going the "happy path" should be exceedingly simple, with features like command prompts for required additional information or "advanced" modes. "Unhappy paths" should be exceedingly debuggable; errors should be clear enough for the user to know whether it's their own error or a bug to report
1. **Knowing when things break**: add more testing and analytics to know when something is breaking, rather than waiting for users to alert us

Speed is a nice to have. Ideally installing and interacting with the CLI should feel performant, but being robust and simple trump speed.

## Progress

- [x] Release [aragonCLI v7](https://github.com/aragonone/product/issues/222) in ~early December, focusing on reducing technical debt and maintaining the existing interface
- [x] Regroup and finalize future roadmap (v8+) with larger external interface changes

**Comment by izqui** [comment]
Amazing post. So excited about how this team is starting to look ❤️

**Comment by sohkai** [comment]
Closing; we have executed on eliminating technical debt and migrated development tooling to the buidler plugin.
