### ISSUE TITLE
App Center installation

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#22]
# Idea
## User story
As as user, I want to be able to discover and install apps from the App Center, so that I can add new features to my organization over time.

Related issues: [1](#)

## Technical requirements
To let the user install apps, we will:
- Implement an easy to read, step by step guide on which aragonCLI commands to run in order to install an app
- We will autocomplete the CLI parameters for the user with data from the particular app they want to install

### Edge cases
- There is an edge case where apps may be not be initialized, or may not have any assigned permissions. In that scenario, we have to guide the user on how to initialize the app and assign permissions to it. [Related issue](https://github.com/aragon/aragon/issues/654)

## Summary

By implementing a tutorial inside the client, we allow users to install apps in the short term, without having to wait until there's a more user friendly solution with a fully fledged UI.

# Prototype

**Comment by sohkai** [comment]
We will evaluate this in the future.
