### ISSUE TITLE
Budgeting features inside Finance

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#23]
*to be documented after kickoff call*

# Idea
## User story
As as user, I want *x, y and z*.

Related issues: [1](#)

## Technical requirements
To let the user perform *x, y and z*, we need to implement *a, b and c*. Those require to implement *d, e and f*.

## Summary

By implementing *a, b and c*, the user will be able to perform *x, y and z* because reasons.

**Comment by sohkai** [comment]
We will evaluate this in the future.
