### ISSUE TITLE
Allow Agent to receive NFTs

### ISSUE THREAD

**Issue by izqui** [aragonone/product#251]
# Idea
## User story
As as user, I want my Agent to be able to receive NFTs.

This is currently blocking Melon from making their DAO the proper owner of their ENS names (currently they are just managing subdomians with Agent)

Related issues: [apps#1036](https://github.com/aragon/aragon-apps/issues/1036)

## Technical requirements
- Easy: Implement ERC721 receiver interface in Agent
- Complex but future proof: Implement 'Agent callback plugins' so users can 'install functions' on Agent (doing a delegate call depending on the function `msg.sig`)

## Tasks

- [x] Contract changes
- [x] Contract deployment
- [x] ~~aragonPM upgrade (first week of Jan.)~~
- [x] ~~A1 blog post (first week of Jan.)~~

**Comment by izqui** [comment]
Bumping this up again as Saint Fame also requested support for Agent being able to receive NFTs

**Comment by izqui** [comment]
PR (implementing the easy option): https://github.com/aragon/aragon-apps/pull/1058

**Comment by sohkai** [comment]
Decided to not do an aragonPM upgrade at the moment.
