### ISSUE TITLE
Fundraising design

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#26]
*to be documented*

# Idea
## User story
As as user, I want *x, y and z*.

Related issues: [1](#)

## Technical requirements
To let the user perform *x, y and z*, we need to implement *a, b and c*. Those require to implement *d, e and f*.

## Summary

By implementing *a, b and c*, the user will be able to perform *x, y and z* because reasons.

- [ ] Paty to Sync

**Comment by jounih** [comment]
I've been talking about this with Luke over the past couple of weeks. It might be worth making this into an epic and splitting it into several user stories. I also think there are different cases of fundraising that could benefit from somewhat optimised experiences for each - would be good to do research on which one we go deep on

-accountable crowdfunding - buying tokens as an investment (replacement for shares with expectation of price increase/dividends as the underlying organisation makes money) in for-profit companies. I think this is a compelling way to add liquidity for investors (while having the accountability that Aragon provides) and global access to funding for early stage companies, but needs clarification around the legal status

-kickstarter style campaigns where fundraising is used to bring a prototype phase product to market, and release of funds tied to specific goals (needs an oracle or a vote to establish if the goals have been met)

-transparent charity fundraising where release of funds is tied to specific goals (needs an oracle or a vote to establish if the goals have been met)

-Patreon style fundraising where buying tokens to support a creator/project give you access to some extras like digital goods but not tokens tied to revenue

-fundraising for tokenised IP rights (selling fractions of publishing rights for songs, movies, books whatever) - I think this could be an interesting one where you are "betting" on your favourite musician/author/filmmaker, supporting them early on but also potentially getting a return on investment by buying fractional publishing rights

-fundraising for open source (I think this could also use any of the above, but I think with Ethereum we could also do nice things to programmatically link revenue to donations - ie. I want to automatically allocate 10% of my DAOs revenue to open source project X, Y and Z) - and make this really frictionless

**Comment by sohkai** [comment]
@dizzypaty to sync with Olivier (pando).

**Comment by dizzypaty** [comment]
I had an in depth chat with Olivier earlier this week to understand the Apiary contracts capabilities and the functionality planned for the front-end. There's still some in flux decisions on the bonding curve design that need to clarify with Luke. But I feel like I have a good enough overview to start sketching some ideas and, as discussed with @luisivan, I will focus on the simplest fundraising use case to begging with and expand from that.

**Comment by luisivan** [comment]
@dizzypaty can you document this one with your current view on Apiary and the goals for it? Thx!
