### ISSUE TITLE
Loading indicator for client

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#27]
# Idea
## User story
As as user, I want to know that the client is loading, instead of seeing a empty screen with no state.

## Summary
By implementing the new loading indicator, we provide feedback to the user about how the client is loading.

## Design
[Figma board](https://www.figma.com/file/QFgvrY5bjKzTY8XqsDmOT9du/Feedback?node-id=158%3A2798)

## Implementation

- [x] New screen loader for the Aragon client (PR: https://github.com/aragon/aragon/pull/770).

**Comment by dizzypaty** [comment]
### Indicators
Loading indicators inform users to wait for an activity to complete. 

The following loading indicators are all **indeterminate** (visualise an unspecified wait time) and relevant to a different loading or syncing state.

![01.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/31a8a160-e906-404e-a506-0d1c8ceebb3c)

![02.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/20ab1d00-7c53-443a-b6ea-33c06d5839c8)

![03.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/e8fdaec7-bc45-405e-b7f3-22a11c44bd6f)

![04.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/54a3ca3a-26c1-46a7-b6ac-f5098cb0492a)

----
[Figma file](https://www.figma.com/file/QFgvrY5bjKzTY8XqsDmOT9du/Feedback?node-id=158%3A2798)

I'll work with @bpierre and @owisixseven on the animations of these components to maintain a consistent style.

**Comment by luisivan** [comment]
Great work. Very well thought of.
