### ISSUE TITLE
System administrators transition

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#28]
- [x] Review existing documentation
- [x] Prepare transition

**Comment by 2color** [comment]
I reviewed the documentation. 

For preparing transition, can you share more concretely what you deem necessary?

We probably want to cover ourselves for failures.

Currently, we have a bunch of externally facing services the product/community rely on and peripheral services for resilience, e.g. backups and monitoring. 

From the docs, the highest priority ones are probably:
- apm serve
- geth ethereum nodes
- rocket chat

@izqui Can you confirm this? Anything else of high priority?

Moving forwards, it's probably best that we test our knowledge with the docs with a drill.

**Comment by izqui** [comment]
Those plus the IPFS node are the highest priority pieces of infrastructure right now, the blogs and discourse forum have way lower maintenance requirements. I'd say the goal for the next few weeks is to completely understand the documentation and be sure that we can react to issues internally.

**Comment by luisivan** [comment]
@izqui more than for the next few weeks, the next few days. Main priority for the dev team should be product, so we cannot spend more than half of @2color's sprint on this

**Comment by 2color** [comment]
I had a call with Paul the DevOps guy. 

I have a pretty good idea how ipfs, apm-serve, and the ethereum nodes are running. 

I've created a diagram (in the infrastructure repository) to visualise the details and high level traffic flow.

For now, this should suffice. I'd say the highest priority would be to improve the alerting mechanism.

**Comment by luisivan** [comment]
Cool. Should we close this off then @2color ?

**Comment by 2color** [comment]
Yep
