### ISSUE TITLE
Inform the user that voting doesn't cost tokens

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#30]
# ✅ Idea
## User story
As as user, I want to be informed that voting doesn't cost tokens.

Related issues: [1](https://github.com/aragon/aragon-apps/issues/362)

## Technical requirements
Possibly display a message on the voting screen.

## Summary
By informing the user that voting doesn't cost tokens, they will be more likely to vote.

# ✅ Design
[Figma board](https://www.figma.com/file/IzKWAhKx1v24pbhsAlGYM3eH/Inform-the-user-that-voting-doesn't-cost-tokens?node-id=0%3A1)

# ✅ Frontend implementation
[GitHub branch](https://github.com/aragon/aragon-apps/tree/survey-voting-no-tokens)

**Comment by dizzypaty** [comment]
We explored a few variations of the copy included in the Info component to communicate users that casting a vote doesn’t cost tokens. 

Here’s the final copy: 

> Performing this action will **not transfer out** any of your tokens. You’ll only have to pay for the [ETH fee]() when signing the transaction.

We can add a link on ‘ETH fee’ to [ETH Gas Station](https://ethgasstation.info/) so users can have more information about the standard gas fee and other relevant links like this article: [Ethereum, Gas, Fuel, & Fees – ConsenSys Media](https://media.consensys.net/ethereum-gas-fuel-and-fees-3333e17fe1dc)

See the attached mockup for further context and here's the [Figma file.](https://www.figma.com/file/IzKWAhKx1v24pbhsAlGYM3eH/Inform-the-user-that-voting-doesn't-cost-tokens?node-id=0%3A1)

![WebApp-1366px - Info-copy-1@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/e8374786-163c-4388-8ae1-4f40bc752b5f)

**Comment by luisivan** [comment]
Great! I think we should link to https://ethgas.io (thx @bpierre for the link) for the gas explanation

**Comment by sohkai** [comment]
@AquiGorka you can find the timestamp of the block through [`web3.eth.getBlock()`](https://web3js.readthedocs.io/en/1.0/web3-eth.html#getblock), which is accessible in the iframe app as [`app.web3Eth('getBlock', <blocknumber>)`](https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.js#L295).
