### ISSUE TITLE
Implement message signing for Aragon apps

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#33]
# ✅ Idea
## User story
As as user, I want to authenticate to apps with my current Ethereum address by just clicking a button.

## Technical requirements
Implement `web3.eth.personal.sign` in aragonAPI.

## Summary

By implementing `personal.sign`, we enable users to authenticate to apps and developers to use that functionality.

#  ✅ Design
[Figma board](https://www.figma.com/file/Zd6kthKiCtkPSdIEzMSXaABu/Message-signing-for-Aragon-apps?node-id=0%3A1)

# Frontend implementation

- [aragon.js PR (contributor)](https://github.com/aragon/aragon.js/pull/261)
- [Aragon client PR (contributor)](https://github.com/aragon/aragon/pull/488)

- [x] @luisivan to talk to Autark and see if they can take on them

**Comment by dizzypaty** [comment]
Here’s a concept of how message signing could work for Aragon app from the Signing panel. 

### UI elements included: 
* Action title and description 
* Connected ETH address (IdentityBadge component)
* App that request the signature (AppBadge component)
* Message that user needs to sign 
	* If the message is human readable text, we will display it by default 
	* If not, the message could be hidden using the available Show/hide patten 
	* Message container (Info component) should have a max. hight and if the contents exceeds this length, a scrolling bar will be display
* ´Sing message´ primary button 

![WebApp-1366px - Sign message generic@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/b2e37d16-7e3d-4202-965b-95418f683e70)

![WebApp-1366px - Sign message generic@2x-1.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/16b3ddb3-9392-4514-8e01-d5bb9eb0f25b)

![WebApp-1366px - Sign message generic@2x-2.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/f1a1fdd9-296a-4ec5-931c-293cc01b4e95)

[Figma file](https://www.figma.com/file/Zd6kthKiCtkPSdIEzMSXaABu/Message-signing-for-Aragon-apps?node-id=0%3A1) with the above assets.

**Comment by luisivan** [comment]
Autark will implement our design, so great news!
