### ISSUE TITLE
Intent context

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#34]
# Idea
## User story
As as user, I want to know context about actions started by he organizations' participants.
I want to see who created a given vote (impossible right now if a token holder creates it), alongside some context about the action.

Related issues: [1](https://github.com/aragon/aragon/issues/452)

## Technical requirements
- Include an `input` parameter in aragonOS forwarding
- Create a UI to let users input context on the signer panel, just before sending the transaction

### Challenges
- Should that context an IPFS hash? Should it be editable after it's sent?

## Summary

By implementing metadata on forwarding, users always know some more context about any given action and the rationale behind it.

**Comment by sohkai** [comment]
Closing; we will evaluate at a future time.
