### ISSUE TITLE
Implement new onboarding

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#40]
# Idea
## User story
As as user, I want to be able to create an organization with multiple rich templates, and know what each of those does.

## Technical requirements
To enhance the onboarding, we will:
- Revamp the onboarding experience
- Revamp the onboarding templates
    - We should include not only templates with the default apps, but also with the Fundraising, Pando and TPS apps

# Design 
- [Figma board](https://www.figma.com/file/C6XsGAydczT3MxwAwimX4N3c/Onboarding)
- [Prototype](https://www.dropbox.com/s/95ht5tntchffn5n/COMPLETE_ARAGON_ONBOARDING.mov?dl=0)

# Implementation

- [ ] First iteration (Sprint 25, 26, 27)
- [ ] Copy finalization (@dizzypaty, @lkngtn, @john-light Sprint 29)

**Comment by luisivan** [comment]
@owisixseven can you link to the early onboarding concept here?

**Comment by ghost** [comment]
> @owisixseven can you link to the early onboarding concept here?

**Onboarding Concept -** https://www.figma.com/file/Hz7YJstizDFoG7FXvfd5pD1A/Onboarding_concept?node-id=0%3A1

**Comment by luisivan** [comment]
Next step: @dizzypaty to test the onboarding design with users

**Comment by ghost** [comment]
# Second iteration 

**Updated to the new design system including:**

-New fields
-Shadows
-Border radius
-Size of typographies
-Hover elements
-illustrations 
-Consistency with the product
-Added new responsive design
-Prototype to view the flow, directionality and consistency with all the screens.

**Check designs on FIGMA** [here](https://www.figma.com/file/cDLkOC1O54yVphU2wooX2CQ0/Onboarding-Voting-Agent-APP?node-id=4%3A5)
**Check video with prototype** [here](https://www.dropbox.com/s/95ht5tntchffn5n/COMPLETE_ARAGON_ONBOARDING.mov?dl=0)
