### ISSUE TITLE
Improve Token Manager copies UX

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#41]
[GitHub Issue](https://github.com/aragon/aragon-apps/issues/509)

**Comment by luisivan** [comment]
plz add the link to the designs here @dizzypaty

**Comment by dizzypaty** [comment]
After reviewing all the comments of the related [Github issue](https://github.com/aragon/aragon-apps/issues/509) and exploring different wording for this action, we’ve decided to change “Assign” for “Add tokens” and keep the words “Remove tokens” for the opposite action. This way, the app front-end doesn’t conflict with the terminology used for the related permissions. 

Also added an informative message communicating what permissions roles (mint & issue tokens) are needed to execute this action. 

In the future, we’ll explore further describing how the permissions are being used and how this maps to the apps UI. 

<img width="1366" alt="WebApp-1366px - main-view@2x" src="https://user-images.githubusercontent.com/7205369/55620103-5be7aa80-579a-11e9-85b9-d17d6c183fa5.png">
<img width="1366" alt="WebApp-1366px - main-view@2x-1" src="https://user-images.githubusercontent.com/7205369/55620118-630eb880-579a-11e9-961d-6f6b774ac3b0.png">



[Figma file](https://www.figma.com/file/Cx2vaUgLFS6wOKvlKV0LMSnr/Apps-copy-ammendements?node-id=11%3A2)

**Comment by bpierre** [comment]
PR https://github.com/aragon/aragon-apps/pull/773
