### ISSUE TITLE
Powered by Aragon

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#43]
We should create a "Powered by Aragon" landing page in which we explain people what it means to be powered by Aragon. We can focus around 3 core ideas:

- Transparency: Your stakeholders always know what's going on
- Governance: Your stakeholders can participate in the future of the organization
- Security: aragonOS secures more than $1m and the smart contracts have been audited by the Whitehat group, Consensys Dilligence and Authio

Then we can offer logos you can get that link to this landing page.

[Related designs](https://wiki.aragon.org/design/powered_by_aragon/)

**Comment by ghost** [comment]
**Designs -** https://www.figma.com/file/XlNbH2ATDZ5SD0gYh70i7WFD/Power_By_Aragon?node-id=94%3A2

**Comment by luisivan** [comment]
Hey @delfipolito! Plz update on this

**Comment by luisivan** [comment]
Pending permission from mentioned projects to use their logos

**Comment by luisivan** [comment]
@delfipolito we need to replace Melonport's logo with Melon's logo at https://github.com/melonproject/branding/blob/master/melon/12_Melon_logo_transparent.png

Otherwise, it's ready to go out!
