### ISSUE TITLE
Integrate user feedback and support system

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#45]
# Idea
## User story
As as user, I want to have contextual help, and an option to submit feedback or get support.

[Related forum post](https://forum.aragon.org/t/on-user-support-and-product-feedback/689)

## Technical requirements
To let the user get contextual help and submit feedback, we will integrate [Help Scout](https://helpscout.com).

We will have a help button across all the app, and users will be able to opt into help, and will be alerted that it will load a third-party script.

## Summary

By implementing Help Scout, we can provide support and also get feedback from users.

## Frontend

PR: [Add helpscout's embedded script](https://github.com/aragon/aragon/pull/758)
Branch: `feature/user-feedback-support`

**Comment by luisivan** [comment]
Plz add the design step to the issue @dizzypaty

**Comment by dizzypaty** [comment]
#### Prototype
https://www.figma.com/proto/RPNNGKB3L8McTXkIbAeLn5yZ/Help-Scout-exploration?node-id=0%3A1&scaling=scale-down

#### Initial visual exploration 
https://www.figma.com/file/RPNNGKB3L8McTXkIbAeLn5yZ/Help-Scout-exploration?node-id=0%3A1

#### Help button 
![WebApp-1366px - main-view@2x](https://user-images.githubusercontent.com/7205369/55621109-e204f080-579c-11e9-91a7-94c4ca45e5e4.jpg)

#### Help widget open 
![WebApp-1366px - main-view@2x-3](https://user-images.githubusercontent.com/7205369/55621106-e03b2d00-579c-11e9-87ab-616eba1e46f6.jpg)
![WebApp-1366px - main-view@2x-2](https://user-images.githubusercontent.com/7205369/55621101-dd403c80-579c-11e9-9119-4528452c6135.jpg)
![WebApp-1366px - main-view@2x-1](https://user-images.githubusercontent.com/7205369/55621070-cd285d00-579c-11e9-9921-f9a634843486.jpg)

Note: We still need to discuss and agree on the color we'll use for the CTA button BG, component header and primary button – cc @owisixseven

**Comment by AquiGorka** [comment]
@luisivan @dizzypaty should the _help-chat_ be rendered for onboarding?

**Comment by luisivan** [comment]
@AquiGorka yes, it should!

**Comment by bpierre** [comment]
Should we have a way to discard this button (and make it reappear from the settings)? Or use a color similar to the secondary button? I’m wondering if it’s not a bit too strong for something that is displayed at all times.

**Comment by luisivan** [comment]
I think that it is fine since we want people to notice it when they upgrade, and then we can listen to user feedback and change the color if needed

**Comment by AquiGorka** [comment]
@luisivan can we double check the copy

**Comment by luisivan** [comment]
Copies are okay and reviewed, the last version on Figma is the right one (https://www.figma.com/file/RPNNGKB3L8McTXkIbAeLn5yZ/Help-Scout-exploration?node-id=0%3A1).

**Comment by luisivan** [comment]
@AquiGorka can you add the frontend implementation section to the issue? Thx

**Comment by dizzypaty** [comment]
# Visual specs
[Figma file](https://www.figma.com/file/RPNNGKB3L8McTXkIbAeLn5yZ/Help-Scout-exploration?node-id=159%3A201)

## Color
Header: Aragon Blue #08BEE5
Title: #212B36
Body copy: #5D6E7F
Link: Aragon Blue #08BEE5
Button: Aragon gradient, see image bellow 

[image:19DE5DA2-45E9-44B4-85B4-73EFE4366102-305-0001DBA3D2A74E2E/Screen Shot 2019-05-14 at 14.01.27.png]

## Size & spacing
Button: 40x40px
Icon inside the button: 16x16px
Touch area: 64x64px (see mock-up)
Help scout module: H:482 x W:336px
Spacing: 24px each side

## Type scale
Title: Overpass Light 20px 
Body copy: Overpass Light 13px
Max width of content container: 350px

# Behaviour 
Integration with Help Scout will allow Aragon users to have contextual chat help and access to help docs. 

When users click on the Help button, an opt-in screen is presented requesting users’ consent to load Help Scout script. This screen will only be displayed once if users allow to proceed.  

While the Help scout module loads, we’ll show an indeterminate loading indicator. We should use the LoadingRing component. 

Users can then access the help module to directly ask any questions or look for relevant content from the knowledge base available. 

If users click anywhere else on the screen while the Help scout module is open, this will close it automatically. If Help is reopened, the module should display the default screen.

Users should be able to dismiss/hide this button permanently from the Organization’s preferences screen. (TBC)

For smaller form factors, the module will be displayed in full screen mode, placing the close button (‘X’) at the top right of the screen. 

Also, the Help button (‘?’), should have a touch target area of 64x64px, allowing for better thumb grip and smoother interaction with it. 

## Mock-ups 

#### Large form factors 

![WebApp-1366px - main-view-1](https://user-images.githubusercontent.com/7205369/57700006-5747c900-7659-11e9-98ea-1ce48c5b8c00.png)

![WebApp-1366px - main-view](https://user-images.githubusercontent.com/7205369/57700024-63cc2180-7659-11e9-8134-9b2e1e738c13.png)

![WebApp-1366px - main-view-2](https://user-images.githubusercontent.com/7205369/57700031-69c20280-7659-11e9-8919-b05c541bad2f.png)

![WebApp-1366px - main-view-3](https://user-images.githubusercontent.com/7205369/57700038-6e86b680-7659-11e9-9c10-1cce512fc91f.png)

#### Smaller form factors 

![Home x 768](https://user-images.githubusercontent.com/7205369/57700099-8d854880-7659-11e9-85bf-f3686121112d.png)
![Home x 768-1](https://user-images.githubusercontent.com/7205369/57700104-8fe7a280-7659-11e9-9d33-041858b4bdad.png)

![Home x 414-3](https://user-images.githubusercontent.com/7205369/57700127-9bd36480-7659-11e9-8503-b9f4b92da9a1.png)

![Home x 414-1](https://user-images.githubusercontent.com/7205369/57700143-a2fa7280-7659-11e9-9364-873bc625e6e0.png)

#### Close button: pressed state 
![Home x 414-2](https://user-images.githubusercontent.com/7205369/57700205-bdcce700-7659-11e9-940a-db60c799909b.png)


#### Content container: max width 350px
![Content Max width 350px](https://user-images.githubusercontent.com/7205369/57700152-a7269000-7659-11e9-891a-2137c425f070.png)
