### ISSUE TITLE
Design test framework for upgrading app contract versions

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#47]
# Idea

We should actually test that existing organizations will work correctly once we've upgraded their apps.

None of the changes (in 0.6) suggested anything major, but still good to at least do a round of smoke testing.

Some thoughts:

- Spin up a fork of the current Rinkeby or mainnet environment
- Create a new organization, with the old apps
- Create some state in these apps
- Upgrade the contracts
- Verify the apps still work as expected

Prototype:

- https://github.com/aragon/aragon-apps/pull/782

**Comment by luisivan** [comment]
Should I update this for 0.8 to 0.9, when we introduce contract changes again? cc @sohkai

**Comment by sohkai** [comment]
I've renamed it so it's more generic.

**Comment by sohkai** [comment]
We will evaluate this in the future as we introduce new contract changes.
