### ISSUE TITLE
Show transactions to vault in Finance app

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#51]
# Idea
## User story
As as user, I want direct deposits to the Vault to be shown in the Finance app as well.
I also want outgoing Vault deposits to be shown.

Related issues: https://github.com/aragon/aragon/issues/776

## Technical requirements
- Track direct deposits to the Vault and show them in the Finance app without description
- Do the same for outgoing transfers

**Comment by luisivan** [comment]
@sohkai would this be showing the deposits directly done to the Vault in the finance app?

**Comment by sohkai** [comment]
@luisivan Can you expand on the context for this issue? Is it to display direct Vault deposits (ones not originating from the Finance app) as separate rows in the Finance app?

These deposits would have less information, but we could give them a bit of text, like "Direct Vault deposit".

Should we also try to track direct Vault transfers (if someone had the permission to directly transfer funds from the Vault)?

**Comment by luisivan** [comment]
@sohkai exactly, both. Documented it in the description now

**Comment by lkngtn** [comment]
Cross posting a relevant discussion from Aragon Chat. https://aragon.chat/channel/general?msg=DhrkmWfkvfQddqcui

**Comment by sohkai** [comment]
Closing; will track in client repo.
