### ISSUE TITLE
Community dashboard

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#53]
# Feasibility

**Aragon GitHub organization**
- Number of first time contributors (create/comment issue, PR, review) (past month)
- Number of repeat contributors  (create/comment issue, PR, review) (past month)
- Top 10 non-Flock contributors

**Aragon forum**
- member growth (w/w)
- post growth (w/w)
- active member growth (w/w)

**Aragon Chat**
- member growth (w/w)
- post growth (w/w)
- active member growth (w/w)

**@AragonProject Twitter**
- Follower growth (w/w)
- Most active engagers (top 20) (past week)
- New engagers (top 20) (past week)
- Most popular posts (top 5) (RT/ like/ engagement/ reach)

**Aragon project blog**
- Views growth (w/w)
- Most viewed post (top 5) (past week)
- Most clicked link (top 5) (past week)

**Aragon project mailing list**
- Subscriber growth (w/w)
- Number of opens (last 2 emails)
- Number of clicks (last 2 emails)
- Most popular links (top 10) (last 2 emails)

**Aragon website**
- Unique visitor growth (w/w)
- Most popular pages (top 5) (past month)
- Top traffic sources (top 5) (past month)
- Click-through on product link
- Bounce rate for home page and product page

**Comment by sohkai** [comment]
We will evaluate this in the future.
