### ISSUE TITLE
0.7 immediate polish

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#56]
**Deployment todos (frontend)**

- aragonUI
  - [x] https://github.com/aragon/aragon-ui/pull/358 (reviewed)
  - [x] https://github.com/aragon/aragon-ui/pull/359
  - [x] [Release 0.37.0](https://github.com/aragon/aragon-ui/releases/tag/v0.37.0)
- aragon
  - [x] https://github.com/aragon/aragon/pull/750 (@bpierre, @sohkai re-review)
  - [x] https://github.com/aragon/aragon/pull/753
  - [x] https://github.com/aragon/aragon/pull/756 (@AquiGorka, @sohkai to review)
  - [x] https://github.com/aragon/aragon/pull/732 (@sohkai to test and merge)
  - [x] https://github.com/aragon/aragon/pull/757
  - [x] https://github.com/aragon/aragon/pull/751
  - [x] ~~Upgrade to `react-springs@8`?~~
- aragon-apps
  - [x] https://github.com/aragon/aragon-apps/pull/828
  - [x] https://github.com/aragon/aragon-apps/pull/829 (@AquiGorka, @sohkai to review)
  - [x] https://github.com/aragon/aragon-apps/pull/825
  - [x] https://github.com/aragon/aragon-apps/pull/784
  - [x] ~~Upgrade to `react-springs@8`?~~
- aragon.js
  - [x] https://github.com/aragon/aragon.js/pull/286 (@2color to re-review)
  - [x] Release new version (@2color or @sohkai)

-------------

**Activity panel**
- [x] Polish (https://github.com/aragon/aragon/pull/756)
  - [x] Progress bar (nice to have)
  - [x] Remove item transition (nice to have)

**Upgrade modal**
- [x] aragon.js (↗️ ⛰️, Brett)
- [x] Improve modal & banner (Pierre) https://github.com/aragon/aragon/pull/737

**App Center**
- [x] Fetch and render the long description (`details_url`, Gorka) https://github.com/aragon/aragon/pull/750
  - [x] Sanity checking text (⛰️ ↘️)

**Finance**
- [x] [Daterpicker issue](https://github.com/aragon/aragon-apps/issues/809) (Gorka) https://github.com/aragon/aragon-apps/pull/819

--------------

**Removed (for later consideration)**:

- Render first hop in notifications, not last one
- Display small size address badge/labels

**Comment by sohkai** [comment]
@luisivan I've pulled out a few items from the activity panel for this release due to unclear design status:

- Rendering forwarded actions
- Small address badges

cc @dizzypaty
