### ISSUE TITLE
Permissions UX enhancements

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#57]
People are a bit confused by permissions, let's think about it

# Implementation

[Aragon](https://github.com/aragon/aragon/pull/899)

**Comment by luisivan** [comment]
@dizzypaty can you add the Design section here with the Figma board? Thanks!

**Comment by dizzypaty** [comment]
@luisivan Sure thing! I'm migrating everything to the team's Figma project (that was giving me some problems this week) and finishing writing the specs. I'll add everything here once that's done : )
