### ISSUE TITLE
Court: Full unit testing

### ISSUE THREAD

**Issue by izqui** [aragonone/product#66]
# Idea
## User story
Test all the components of the court system with a unit testing strategy. Bear in mind the following list of "nice to have"s:
- Avoid mocking unnecessarily, only when there is no other option
- Use test-helpers module provided in apps
- Implement reusable helpers stuff instead of custom non-exported functions 
- Unify testing approach along the test suite

## Implementation
- [ ] Court lifecycle (disputes, appeals, final round appeals)
- [x] CRVoting
- [ ] Subscriptions
- [ ] HexSumTree
- [x] Court accounting - [PR](https://github.com/aragon/aragon-court/pull/67)
- [x] Jurors registry - [PR](https://github.com/aragon/aragon-court/pull/72)
- [ ] Agreements

**Comment by luisivan** [comment]
@izqui can you expand on this one? Is it just coding tests for the contracts?

**Comment by izqui** [comment]
Yes

**Comment by facuspagnuolo** [comment]
Closing this issue since we have created better-described issues the court repo.
