### ISSUE TITLE
Re-implement the Governance page

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#68]
# Idea
## User story
As as user, I want to understand the AGP process without having to read too much.

## Technical requirements
Implement a landing page that beautifully explains it.

## Summary
By implementing a landing page to explain the AGP process to people, and provide a link for them to participate by buying ANT.

**Comment by ghost** [comment]
Wireframe - https://www.figma.com/file/RK6iG9PfLgJGNDyXnDzTIQmH/AGP_CONCEPT?node-id=0%3A1
