### ISSUE TITLE
Fundraising landing page

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#70]
# Idea
## User story
As someone who wants to use Aragon to fundraise, I want to know how it would help me reach by fundraising goals.

## Technical requirements
Implement a landing that talks about the fundraising app and the ways I can use it.

## Summary
By implementing a landing page on the fundraising use case, we will get feedback from future users and learn from it.

## Progress

- [x] Review by @john-light (Sprint 35)
[Staging enviroment](https://delfipolito.github.io/aragon-website/fundraising/)
- [x] Jack to confirm website finalization (Sprint 38)

**Comment by ghost** [comment]
Design ready! - https://www.figma.com/file/ftXnDiMnJNjeX6p4UlL8ka/Fundraising
