### ISSUE TITLE
Link for sharing labels

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#72]
# Idea
## User story
As as user, I want to easily share my locally-stored labels with other people.

## Technical requirements
To let the user share their labels, we could implement a system where the JSON file is parsed into the URL, and then shared with a link.

The Aragon client would recognize the fragment in the URL, and ask the user if they wanna import the labels.

## Summary
By implementing label sharing, we enable users to instantly share their locally-stored identities.

## Frontend
PR: https://github.com/aragon/aragon/pull/775
Branch: `feature/share-identities`

**Comment by dizzypaty** [comment]
### Share custom labels via link 

#### Large form factor 

Note changes:
* Added a 'Share' button 
* Moved the position of the 'Remove labels' button to the right
* Every table row has a checkbox control, position to the left of the custom label, that allows for individual item selection. The table header also displays a global one that allows for the selection of all table rows.

#### Behavior

On click on the 'Share' button, a modal is displayed allowing users to copy the URL (that contains the .json file hash).

![WebApp-1366px - preferences-1@2x.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/783d1edf-ad70-4d4d-82a8-8aa770c4b60c)

![WebApp-1366px - preferences-1@2x-1-1.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/0e377109-a41a-4ace-bcb8-6921f275ed4c)

When users open the URL shared with them, they land on this confirmation page, where they can see the labels shared with them and can decide to uncheck any of them before they get them locally.

![WebApp-1366px - preferences-1@2x-11.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/83488a6a-e852-45dc-8670-ba0e8145ec73)


**Note:** We should display a toast communicating users that their action has been completed successfully.

![WebApp-1366px - preferences-1@2x.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/dc55a05b-ccd8-45c5-87b8-70733693c410)

#### Small form factor 
![Mobile preferences@2x.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/1e85da7f-b517-4d48-ac19-cf9a5fdc51fe)

**Note:** On mobile, we need to check if web3 browsers allow for invoking the native OS sharing panel. If so, people can directly share the link with other apps or contacts. If this is not possible, we'll follow the above solution.

![Mobile preferences@2x-1.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/023bfecb-c5dd-4daa-a09c-34edfcb36246)

![Group(4)(1).png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/e87d4aff-a2a7-4197-b4d3-b89788c8db47)

[Figma file](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=14%3A0)

**Comment by luisivan** [comment]
@dizzypaty we also need some UI for when you access a shared link. It should ask the user if they wanna import the labels, before importing them

**Comment by dizzypaty** [comment]
@luisivan this is the mockup number 3 (and also the last mobile one) that I added above. 

Described behavior: "When users open the URL shared with them, they land on this confirmation page, where they can see the labels shared with them and can decide to uncheck any of them before they save them locally."

We can reuse the same table we have in the preferences screen as a way for users to preview and select what they are about to import before they do.

Let me know if you have something else in mind : )

**Comment by luisivan** [comment]
Got it! That makes a lot of sense. This seems to be ready to be implemented then!

**Comment by AquiGorka** [comment]
@dizzypaty and @luisivan:

How should we deal with conflicts? Is this a first iteration where we:
a) Remove existing local identities and import all from `json` (overrides all local identities)
b) Keeps existing local identities and override with data from `json` for conflicts (overrides local identities on item case)
c) other ideas/suggestions

Toast for sharing, should the copy read in the lines of:
"Link copied"
and, should we show a toast when the user successfully saves the imported identities?
"Labels have been imported"

**Comment by dizzypaty** [comment]
@AquiGorka I need to work on a screen that allow users to decide what they want to do in the case of conflicts. At the moment we are doing option [a] --> overriding everything. But we should take this opportunity to allow for more user control. I'll try to get something to show you on Wednesday. 

Re toasts: I've added a mock up on the comment above displaying the toast component after the user's action has been successfully completed. Also in separated issues (I believe Delfi's working on them) for the other actions within these 'Manage labels' screens. This is my suggestion for the copy we should use on these toasts: 

* Custom label added 
* All custom labels removed 
* Custom labels exported 
* Custom labels shared 
* Custom labels imported 

And I was thinking that, in case of an error, we could add a ‘Retry’ action to the toast or use another component. I’d like to discuss it with Adri.

**Comment by luisivan** [comment]
Let's see what's the implementation effort of having "merging strategies", but if it's too much, I'd just release the first iteration with override by default.

**Comment by AquiGorka** [comment]
@luisivan if we have the sharing button do we need the export button?

**Comment by luisivan** [comment]
Yeah, you may want to export to a JSON file instead of sharing a link

**Comment by dizzypaty** [comment]
We could potentially present only one button (i.e.: Share) and they provide users with the choice on the modal: [a] Export them via .json file or [b] Share them via link. This will make the preferences screen cleaner, but in case, we do need both options : )

**Comment by luisivan** [comment]
True, that sounds good to me as well
