### ISSUE TITLE
Include edit label button in the tables' action dropdown

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#73]
# Idea
## User story
As as user, I want to edit a label for an address when in a table. I expect to be able to do that in the table's action dropdown.

## Technical requirements
Trigger the edit label action when clicking the *Edit label* item on the action dropdown.

## Summary
By implementing this feature, we satisfy the expected behavior that users have.

**Comment by dizzypaty** [comment]
![WebApp-1366px - main-view@2x(4).jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/069c9137-2ed4-4240-badd-d3668512bae9)

[Figma file](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=16%3A1473)
