### ISSUE TITLE
Implement compact address badges

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#76]
## Designs

- [Completed designs](https://github.com/aragonone/product/issues/76#issuecomment-488029438)

## Implementation

- [x] aragonUI  [PR](https://github.com/aragon/aragon-ui/pull/365) | [Working branch](https://github.com/aragon/aragon-ui/tree/compact-address-badges)
- [x] aragon/aragon [PR](https://github.com/aragon/aragon/pull/769) | [Working branch](https://github.com/aragon/aragon/tree/compact-identity-bagde)
- [x] aragon-apps [PR](https://github.com/aragon/aragon-apps/pull/837) | [Working branch](https://github.com/aragon/aragon-apps/tree/voting-identity-badge)

**Comment by dizzypaty** [comment]
### Compact address badge
---
![Group 38.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/a4685731-dab6-4c14-8ad3-28f990fa026c)

### Examples in context 
---
#### Voting cards

![WebApp-1366px - Voting main view.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/3ff9ae03-b72e-4a2f-8545-0400f476594b)

#### Signer panel

![WebApp-1366px - main-view.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/0fd8b05f-a719-48d7-9451-2b030a04de2b)

#### Preferences empty state

![WebApp-1366px - preferences-1.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/13b2be71-3b78-4cc8-b93f-8f787467abec)

#### Activity panel

![WebApp-1366px – Fundraising-main-view.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/54b140dd-4dca-4cfb-a9fe-79c766d80f05)


[Figma file](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=42%3A3560)

**Comment by sohkai** [comment]
@delfipolito Looking over the current client, it looks like the following usages of the `IdentityBadge` should be compact (assuming the rule is to use the compact form only inside inline text):

- [`EmptyLocalIdentities`](https://github.com/aragon/aragon/blob/master/src/components/Preferences/EmptyLocalIdentities.js) (see [screenshot](https://camo.githubusercontent.com/e156f7f7afabeb206cb2a152f34cd7f9da3bf72d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563306538326234636430336232333439383730653432312f31336232626537312d336237382d346363382d623933662d386637383734363761626563))
- [`ActionPathsContent`](https://github.com/aragon/aragon/blob/master/src/components/SignerPanel/ActionPathsContent.js#L54) (see [screenshot](https://camo.githubusercontent.com/adf06f78e967964afdeb7f37920767eba66caded/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563306538326234636430336232333439383730653432312f30666438623035662d613731392d343864372d393435312d326230333061303464653262))

Additionally, the following components do not currently use the `IdentityBadge`, but should start using its compact form:
- aragon/aragon's [`ActivityItem`](https://github.com/aragon/aragon/blob/master/src/components/Activity/ActivityItem.js#L90) (see [screenshot](https://camo.githubusercontent.com/b71c1988a5f573568089d6ef76b628519526116c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563306538326234636430336232333439383730653432312f35346231343064642d346463612d346366622d613966652d373963373636643830663035))
- Voting's [`VoteText`](https://github.com/aragon/aragon-apps/blob/master/apps/voting/app/src/components/VoteText.js#L8) (see [screenshot](https://camo.githubusercontent.com/89fea1273edc5e4670ae89635ad27ec7402f441f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563306538326234636430336232333439383730653432312f33666639616530332d623732652d346132662d383534352d303430306634373635393462))

-----------------

@dizzypaty The Permissions app has this usage of the `IdentityBadge` that could be argued is "inline", but I don't think it needs to be adjusted now:

<img width="1192" alt="Screen Shot 2019-05-03 at 4 13 17 PM" src="https://user-images.githubusercontent.com/4166642/57143129-7a06f180-6dbe-11e9-8ef4-bc5bf10f5d49.png">

**Comment by luisivan** [comment]
Hey @delfipolito! Can you add the Frontend implementation section to the issue? Also, please note that you will also need to coordinate with @dizzypaty in order to put the new compact component in all different places where it's needed. The basic rule is the following: everywhere where it's displayed with inline text. @dizzypaty feel free to expand if there's any other usage rule that I missed.
