### ISSUE TITLE
Show confirmation modal before removing all custom labels

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#77]
# Idea
## User story
As as user, I want to make sure I don't accidentally delete all my custom labels.

## Technical requirements
To let the user rest assured that they will not accidentally delete all their labels, we need to implement a confirmation modal.

## Summary
By implementing this feature, users can rest assured about the safety of their labels.

## Frontend
[PR](https://github.com/aragon/aragon/pull/773)
[Working branch](https://github.com/aragon/aragon/tree/confirmation-modal-remove-labels)

**Comment by dizzypaty** [comment]
### Confirmation modal for removing custom labels action

![WebApp-1366px - preferences-1@2x-1.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/f824354a-103d-4479-8259-d4aded39bc1b)

![WebApp-1366px - preferences-1@2x.jpg](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/44cde479-122d-4351-adda-8662feae6094)

[Figma file](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=14%3A0)
