### ISSUE TITLE
Revamp info boxes

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#78]
# Idea

Info boxes now are not very consistent. Some have icons, some title, and some just a body. Their visual style is also not very beautiful. Let's re-think and standardize how we use info boxes.

**Comment by ghost** [comment]
**New info boxes added into the new Design System / Components / Info Boxes** - https://www.figma.com/file/98FwQUG81AmlEZ3KXF10wr/Design-System?node-id=139%3A1

**Comment by luisivan** [comment]
Sent feedback on Figma!

**Comment by luisivan** [comment]
@owisixseven  can you update the link with the link to the specific part? The link above just goes to the design system

**Comment by ghost** [comment]
Hey @luisivan i can't link a specific artboard on Figma, sorry. This is the main link, and you can find the info boxes into **-In progress-** page, and go to the **first artboard** (01-Components "Alerts").

https://www.figma.com/file/98FwQUG81AmlEZ3KXF10wr/Design-System?node-id=299%3A2

![01. Components - Alerts.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/45604aff-ddf3-42b3-87ab-307bfce68d4a)

**Comment by luisivan** [comment]
Thanks @owisixseven!
