### ISSUE TITLE
Replace last step in signing with notification bubbling

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#79]
# Idea
## User story
As as user, I want to have my attention drawn to the activity center when signing a transaction, since that's where I will follow the activity regarding the transaction.

## Technical requirements
Replace the very last step in the transaction panel with a more prominent notification animation.

## Summary
This feature lets users be more aware of the activity panel.

**Comment by luisivan** [comment]
@dizzypaty @owisixseven  do we currently have any design or animation for this interaction?

**Comment by dizzypaty** [comment]
@luisivan we have some ideas / early sketches but nothing defined yet. I'd really like us to address this together with the notifications & optimistic UI redesign.

**Comment by luisivan** [comment]
Cool, so not coming for 0.8, right?

**Comment by dizzypaty** [comment]
No, I don't think it was in scope. What it needs some thinking and might require some changes for 0.8 it's the activity panel itself (position & open/close interactions, scrolling, etc.). We'll def have a look at it next week in more detail and specify the changes. After 0.8, we will rethink the entire creating and signing tx panel flow.

**Comment by luisivan** [comment]
Cool! Will then just leave this open for now

**Comment by sohkai** [comment]
We will evaluate this in the future.
