### ISSUE TITLE
Enhance Radspec strings

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#83]
- Add forwarder helpers? (like Voting forwarded would have `A voting will be created`)

**Comment by sohkai** [comment]
I don't see radspec as the place to put these types of annotations.

We already have this forwarding information in the signing panel, and, when radspec is used in the individuals apps, they usually don't need this type of information (e.g. Voting will only describe what it's going to do, not that it created a vote).

Where were you envisioning adding this type of annotation?

**Comment by luisivan** [comment]
The idea came up when talking about permissions, to have a way to say *Maria has permission to withdraw funds from Finance, and a voting is needed on Voting to re-grant or revoke that permission*. Basically right now we give it for granted what the forwarding action does (in Token Manager, it forwards if the sender is a token holder, Voting creates a new vote etc.) but maybe it should be more explicit? Would love your thoughts on that!

**Comment by sohkai** [comment]
Hmm, for this I think we already have the relevant radspec descriptions (they're available on each app's `forward()` function). You can see them in use from the signing panel:

<img width="415" alt="Screen Shot 2019-05-07 at 3 58 06 PM" src="https://user-images.githubusercontent.com/4166642/57305186-ed6f7280-70e0-11e9-8d82-6e0b05746cb9.png">

The descriptions in the "Action Requirement" box come from radspec.

**Comment by luisivan** [comment]
That is true, thanks for noticing. Closing this
