### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#84]
# Idea
Theme the Help Scout knowledge base with our own style.

# Design
[Figma board](https://www.figma.com/file/LdjsE4sf6ThhQvlBp1hrFF3Z/Help-Scout?node-id=0%3A1)

**Comment by ghost** [comment]
**Help Scout with the new guidelines and new illustrations** -https://www.figma.com/file/LdjsE4sf6ThhQvlBp1hrFF3Z/Help-Scout?node-id=0%3A1

**Comment by luisivan** [comment]
I think this should go on the other issue, this one is for the knowledge base UI (e.g. https://aragon.helpscoutdocs.com/)

**Comment by ghost** [comment]
This is the new design oriented to the new Knowledge base. All the visual style are aligned with our design styleguide of UI websites. 

Home preview - [Figma board](https://www.figma.com/file/dgym3k5hFgJRG5WUOwDn2ssv/Aragon-Knowledge-Base?node-id=0%3A1)

![index.jpg](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/785277f5-ac18-41c7-b099-420ae404e7ce)

For a best practique we can use a column of 6 items on the highlight themes*

Interior preview - [Figma board](https://www.figma.com/file/dgym3k5hFgJRG5WUOwDn2ssv/Aragon-Knowledge-Base?node-id=0%3A1)

![Aragon-Knowledge-Base.jpg](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/d33ea68e-3fb8-4fb6-8114-0247fbbbd68c)

We also have the responsive versions included on the Figma's file.

**Comment by luisivan** [comment]
Amazing!!

**Comment by ghost** [comment]
@delfipolito the Figma board [here!] (https://www.figma.com/file/dgym3k5hFgJRG5WUOwDn2ssv/Aragon-Knowledge-Base?node-id=0%3A1)
