### ISSUE TITLE
New visual style for the client

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#86]
## Idea

Re-think and re-design:
- [x] Top bar and side bar
- [x] Main app modules

## Design
[Figma board](https://www.figma.com/file/98FwQUG81AmlEZ3KXF10wr/Design-System?node-id=139%3A1)

## Implementation

[aragonUI](https://github.com/aragon/aragon-ui/pull/391), [Aragon](https://github.com/aragon/aragon/pull/826)

- [x] New structure with the header client side
- [x] Use aragonUI 1.0 / the new theming system
- [x] Make `Layout` work with internal apps (excluding the MenuPanel width)
- [x] Home
- [x] Settings ([PR](https://github.com/aragon/aragon/pull/896), @sohkai Sprint 27)
- [x] Toggle MenuPanel (@sohkai Sprint 27)
- [x] Organization switcher (@sohkai Sprint 27)
- [x] Activity panel ([PR](https://github.com/aragon/aragon/pull/929), @sohkai Sprint 27)
- [x] Signer panel (@sohkai Sprint 27)
- [x] Account widget (Sprint 29)
- [x] [Global error](https://www.figma.com/file/M4CmY2PDYgWtQxOXEPopCaJF/Global-Error?node-id=0%3A1) (@sohkai, @AquiGorka Sprint 29)
- [x] 0.8 upgrade showcase + radspec

**Comment by luisivan** [comment]
@owisixseven can you add the Design section to this issue with the Figma board? Thanks!

**Comment by ghost** [comment]
**Design system v1** - https://www.figma.com/file/98FwQUG81AmlEZ3KXF10wr/Design-System?node-id=139%3A1

**Comment by luisivan** [comment]
If you are all in Madrid next week, I think it'd be great if you can just all meet for a whole day or couple of days to work alongside @bpierre on making sure he has everything he needs to start with the changes on aragonUI cc @dizzypaty @owisixseven

**Comment by ghost** [comment]
Perfect @luisivan @dizzypaty @bpierre

**Comment by luisivan** [comment]
needs #79
