### ISSUE TITLE
Add "Upgrade all" button to App Center

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#90]
# Idea
## User story
As as user, I want to upgrade multiple apps at once from the App Center.

## Technical requirements
To let the user upgrade multiple apps at once from the App Center, we need to implement a button that does that.

Related issues: [1](https://github.com/aragon/aragon/issues/763)

# Design
![](https://user-images.githubusercontent.com/7205369/57214697-0d246f00-6feb-11e9-8474-195889939565.png)

# Frontend implementation
[PR](https://github.com/aragon/aragon/pull/795)

Behavior:
- Show the button when more than one app has updates available. Hide it when not

**Comment by sohkai** [comment]
@dizzypaty Should we use an icon instead of the button in a mobile layout?

And to check on the behaviour: this button should only appear on the top level navigation (e.g. not when you're viewing the details of a particular app)?

**Comment by dizzypaty** [comment]
@sohkai Yes! we needed an icon for this. I created this one: 

<img width="42" alt="Upgrade-icon" src="https://user-images.githubusercontent.com/7205369/57943823-591dc080-78d5-11e9-990b-e0359f899584.png">

But it'd be great if @owisixseven could review it and add it to the icon set : )


> And to check on the behaviour: this button should only appear on the top level navigation (e.g. not when you're viewing the details of a particular app)?

Exactly, it belongs in the main view, on the header. We shouldn't show it on any specific app details view. If an app contains an upgrade, we'll display a CTA button within the first section of that screen, next to the app name and icon.

**Comment by luisivan** [comment]
@delfipolito plz remember to link the PR in the description under "Frontend implementation"

**Comment by ghost** [comment]
@dizzypaty reviewed and added into the icon set!
