### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#94]
# Idea
## User story
As as user, I want to be notified about important events in organizations that I care about.

Related: 
[Forum post](https://forum.aragon.org/t/push-notifications-on-the-aragon-client/855)
[Figma designs](https://www.figma.com/file/PSd8Met26ifmkza2qnRv6WTC/Email-notifications?node-id=4%3A5079)

## Technical requirements
- Frontend to let users choose events from the organization's apps
- Server that registers those notification preferences alongside with an email address. It also receives webhooks when an event happens, and sends an email to the recipient

[Introduction forum post](https://forum.aragon.org/t/push-notifications-on-the-aragon-client/855)

## Technical notes from @sohkai 

Maintain a user-facing notification service that satisfies the following requirements:

- **CRUD application**: viewing, subscribing, and unsubscribing emails from event types
  - Integrated with the Aragon client via HTTP calls
  - Standardized API endpoints, so users could _technically_ run their own email service and connect the Aragon client to it
  - User authentication based on email
- **Event notifier**: polls for / receives new events
- **Email handler**: sends emails to subscribed accounts
  - Emails are still to be designed, but will include at least the following dynamic content:
    - Time
    - Block number
    - Transaction hash
    - Sender of the transaction (`msg.sender`)
    - Description

Initially the notification method will consist only of emails.

To learn about new events, the event notifier can poll on pre-determined intervals from an ETH node or similar API.

The integration with the Aragon client will likely involve a new preferences screen with the ability to list and subscribe to new events based on an email inputted by the user.

<details>
<summary>Reliability</summary>
  
- Uptime: as high as possible
- Consistency: ability to recover events missed during downtime
</details>

<details>
<summary>Security</summary>
 
- Users should be authenticated against their email whether they want to subscribe or unsubscribe to an event
- Spam registrations may be a problem, given that anyone could put any email address in the Aragon client
</details>

**We should aim to ship a useful notification service that is as reliable as possible in the shortest amount of time. It does not have to be very scalable from the beginning.**

### Future

A number of extensions are possible, which may influence the service's initial design:

- A specialized frontend for the CRUD applilcation, allowing users to directly interact with this service outside of the Aragon client
- Additional notification methods (e.g. SMS, push notifications)
- Real-time notifications
- Easy way for users to run the service themselves, if desired

In particular, additional notification methods will likely involve additional handlers, and real-time notifications will require specialized event notifiers (potentially amongst other infrastructure for queue management).

### TODO
- [ ] add an endpoint to delete multiple subscriptions

### Scout / Event API

To reduce scope and maintenance overhead, we are evaluating whether [Scout](http://scout.cool) is able to provide us a reliable API that mimics what we'd require from an ETH node directly.

Scout are a good fit because they already host the required ETH infrastructure and index the relevant events for the analytics charts. As opposed to the Aragon client, it is not as important for the notification service to be fully censorship-resistent from the beginning (and if someone truly wanted to be, they would run the service themselves).

Scout has published their [latest event query API](https://documenter.getpostman.com/view/1590956/S1TSafQj?version=latest) onto a staging environment and are available on Rocket Chat for questions / concerns. In particular, it is unknown right now how scalable their service can be, and what the latency will be like.

They are expected to have a stable environment by the end of June or early July.

### Event notifier

To reduce initial scope, and keep things simple, I initially envision a database holding Ethereum addresses, a list of event signatures we care about for an address, and an address' "last checked" block (that may be a block safe from re-orgs).

The notifier can poll the event API periodically (5-10min is likely fine for now) to check for new events on a particular address, and send them to the email handler. The email handler can filter for which events are relevant for which emails, and send emails accordingly.

In cases where any component dies or stops working (including an external API, e.g. the email sender), we simply don't advance the last checked block for any addresses.

### Dynamic email content

The event description is an unknown that is mostly orthogonal to this service. We may enhance radspec to work on events, or use a hardcoded mapping between event signature to string for now.

## Notes

- No particular technology choices have been made yet, but using node is preferred unless there are very compelling reasons to use a different language since almost everything else is done in JS
- Although separated for ease of description, the event notifier and email handler can be combined or further split as desired
  - Particularly, in the interest of making recoverability easy, we may want to bundle the two together in the beginning (so the two fail together, to prevent the event notifier from advancing if the email handler is down)
  - Bundling the two also makes it much easier for users to run the service themselves in the future
- User authentication will most likely take the form of one-time tokens emailed to users, since this is the only method we have of authenticating them.

**Comment by luisivan** [comment]
Sprint 14: Just kickoff meeting for the high-level scope, no design

**Comment by luisivan** [comment]
Had a kickoff meeting, next step is @sohkai to have a meeting with Scout in order to define their technical deliverable.

We can start design work on this now.

**Comment by luisivan** [comment]
Goal for sprint 17: complete spec for our cloud infra for this

**Comment by 2color** [comment]
Following our discussion:
- We will use a magic link sent by email for a password-less experience
- After the user enters the email, an email will be sent. Upon clicking it should:
  - verify (by calling the service) 
  - redirect the user to the Aragon client and allow the user to select events to subscribe to 
- The same page should allow unsubscribing from events too

Notes:
- For security reasons it's highly recommended to set an expiration on magic links  (https://security.stackexchange.com/questions/129846/implementing-an-autologin-link-in-an-email). I'll research and see how that fits into our implementation.

**Comment by 2color** [comment]
Closing in favour of https://github.com/aragonone/product/issues/157 and
https://github.com/aragonone/product/issues/158
