### ISSUE TITLE
Aragon Design Guidelines v1

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#95]
# Idea
## User story
As someone building on Aragon, I want to learn how to adhere to the design guidelines for building my app.

## Technical requirements
Implement a section of the dev portal with all our design guidelines.

# Design
[Figma board](https://www.figma.com/file/98FwQUG81AmlEZ3KXF10wr/Design-System?node-id=269%3A2)

# Implementation
- [x] [Working branch](https://github.com/aragon/hack/tree/design-guidelines)
- [ ] Content

**Comment by luisivan** [comment]
@owisixseven can you add the Figma board to the Design section? Thanks!

**Comment by ghost** [comment]
Feedback v1 on https://www.notion.so/aragon/Feedback-guidelines-a6a18469fcfa4ee6bec6da42676c5e61 - @delfipolito

**Comment by sohkai** [comment]
To do after 0.8: @dizzypaty to finalize content

**Comment by luisivan** [comment]
Closing since first iteration is done -- new issue for full content at https://github.com/aragonone/product/issues/95
